# Generated by Django 4.2 on 2023-04-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellerid',
            field=models.ManyToManyField(to='users.seller'),
        ),
    ]
